"""show table implemented

Revision ID: 5fba58c60cd1
Revises: 1d24938a5d29
Create Date: 2020-08-10 21:41:54.637135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fba58c60cd1'
down_revision = '1d24938a5d29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show',
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('artist_id', 'venue_id')
    )
    op.add_column(u'Artist', sa.Column('seeking_description', sa.Text(), nullable=True))
    op.add_column(u'Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.add_column(u'Artist', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'Artist', 'website')
    op.drop_column(u'Artist', 'seeking_venue')
    op.drop_column(u'Artist', 'seeking_description')
    op.drop_table('show')
    # ### end Alembic commands ###
