"""venue columns added without genres

Revision ID: 9d80d82969ee
Revises: 094373e34f80
Create Date: 2020-08-08 19:44:32.620063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d80d82969ee'
down_revision = '094373e34f80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('Venue', sa.Column('talent_description', sa.Text(), nullable=True))
    op.add_column('Venue', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'website')
    op.drop_column('Venue', 'talent_description')
    op.drop_column('Venue', 'seeking_talent')
    # ### end Alembic commands ###
